LizardByte/Themerr-jellyfin

- .github/workflows/CI.yml
Fix yamllint whitespace warning in CI.yml
> ci: fix lint whitespace warning

- CHANGELOG.md
- Dockerfile
- Fix final copy operation in Dockerfile. It was copying the `artifacts` directory instead of the contents of the directory.
- Rename the destination directory to `themerr-jellyfin` for consistency.
- Update changelog to v0.0.2
> docker: fix final copy operation

- Dockerfile
- Removes `--link` arg from final COPY step, which prevents the docker mod from loading the plugin properly.
> docker: remove link arg from final copy

- Dockerfile
Revert removing `--link` arg. It has no effect on the final published image. Issue with docker mod is tracked here: https://github.com/linuxserver/docker-mods/issues/575
> docker: revert removing `--link` arg

- .github/workflows/CI.yml
Since .NET 7.0.200 SDK there is an error with using the action from `oddstr13/jellyfin-plugin-repository-manager`. That repo seems to be somewhat inactive so submitting a fix here by pinning the .NET version as well.
See here for the upstream fix: https://github.com/oddstr13/jellyfin-plugin-repository-manager/pull/85
Referenced jellyfin action jellyfin/jellyfin-meta-plugins/.github/workflows/publish.yaml
> ci: pin dotnet version to 6.0.x

- .github/workflows/ci-qodana.yml
Qodana will now run in the source code repo, and a dispatch event will be sent to qodana-reports to publish the artifacts. There are benefits to running the qodana action in the source code repo which include the ability to comment on the PRs (changed and unchanged files).
> qodana: refactor workflow

- .readthedocs.yaml
Remove depreciated option from rtd config.
> docs: remove depreciated system_packages option from readthedocs config

- Dockerfile
Linuxserver.io docker mods require that all mod files are contained on a single layer.
- Fixes #68 
> fix(docker): use single layer for deployed image

- dockermod_root/etc/s6-overlay/s6-rc.d/init-mod-jellyfin-themerr-config/run
- dockermod_root/etc/s6-overlay/s6-rc.d/init-mod-jellyfin-themerr-config/type
- dockermod_root/etc/s6-overlay/s6-rc.d/init-mod-jellyfin-themerr-config/up
Change encoding from `UTF8 with BOM` to `UTF8` for s6 init files.
- Fixes #68 
> fix(docker): remove BOM from file encoding of s6 init files

- .github/workflows/CI.yml
- Jellyfin.Plugin.Themerr.Tests/Jellyfin.Plugin.Themerr.Tests.csproj
- Jellyfin.Plugin.Themerr.Tests/TestThemerrManager.cs
- Jellyfin.Plugin.Themerr.Tests/Usings.cs
- Jellyfin.Plugin.Themerr.sln
- Jellyfin.Plugin.Themerr/ThemerrManager.cs
- README.rst
- codecov.yml
This "should" fix themes being downloaded in the wrong audio container. Currently they are being downloaded in `WebM`, this changes that to be an `Mp4` container with no video stream.
Additionally, unit testing is added using `Xunit`.
- Fixes #97 
> fix(themes): fix incorrect audio container and add unit testing

- .editorconfig
- Directory.Build.props
- Jellyfin.Plugin.Themerr.Tests/FixtureCollection.cs
- Jellyfin.Plugin.Themerr.Tests/FixtureJellyfinServer.cs
- Jellyfin.Plugin.Themerr.Tests/TestThemerrManager.cs
- Jellyfin.Plugin.Themerr/Api/ThemerrController.cs
- Jellyfin.Plugin.Themerr/Configuration/PluginConfiguration.cs
- Jellyfin.Plugin.Themerr/Plugin.cs
- Jellyfin.Plugin.Themerr/ScheduledTasks/ThemerrTasks.cs
- Jellyfin.Plugin.Themerr/ThemerrManager.cs
- docs/source/contributing/testing.rst
This PR adds SonarAnalyzers.CSharp and StyleCop.Analyzers. I mostly followed this blog post (https://dev.to/srmagura/c-linting-and-formatting-tools-in-2021-bna). They use VS Code, but everything there works in Rider just as well.
> style: add Sonar and StyleCop Analyzers

- Jellyfin.Plugin.Themerr/ThemerrManager.cs
Fixes a bug where previously unhashed theme songs would not be migrated.
> fix: unhashed themes will be re-added

- .editorconfig
- Jellyfin.Plugin.Themerr.Tests/FixtureJellyfinServer.cs
- Jellyfin.Plugin.Themerr.Tests/TestThemerrManager.cs
- Jellyfin.Plugin.Themerr/Api/ThemerrController.cs
- Jellyfin.Plugin.Themerr/ThemerrManager.cs
This PR adds the ThemerrDB issue (add/edit) url in the logs, when a movie is missing from our database.
> fix: improve logging when movie not in ThemerrDB

- Jellyfin.Plugin.Themerr.Tests/FixtureJellyfinServer.cs
- Jellyfin.Plugin.Themerr.Tests/TestThemerrManager.cs
- Jellyfin.Plugin.Themerr/ThemerrManager.cs
When Themerr creates a github issue template URL, it only encodes spaces through .replace() and not reserved characters.
This PR simply changes .replace() with Uri.EscapeDataString
Closes #292 
> Change title space encoding to full url encoding for github issues

- Jellyfin.Plugin.Themerr/Api/ThemerrController.cs
Fixes translations issues reported in #296.
> fix: ensure ui falls back to english

- .github/workflows/CI.yml
- Dockerfile
- Jellyfin.Plugin.Themerr.Tests/Jellyfin.Plugin.Themerr.Tests.csproj
- Jellyfin.Plugin.Themerr.Tests/TestHelper.cs
- Jellyfin.Plugin.Themerr.Tests/TestThemerrController.cs
- Jellyfin.Plugin.Themerr.Tests/TestThemerrManager.cs
- Jellyfin.Plugin.Themerr/Api/ThemerrController.cs
- Jellyfin.Plugin.Themerr/Jellyfin.Plugin.Themerr.csproj
- Jellyfin.Plugin.Themerr/ScheduledTasks/ThemerrTasks.cs
- Jellyfin.Plugin.Themerr/ThemerrManager.cs
- build.yaml
Bump jellyfin controller from 10.8.13 to 10.9.0.
- Resolves #310 
> fix: bump Jellyfin to 10.9

- docs/source/conf.py
- Dynamically determine dotnet and jellyfin versions for building source code docs.
> docs: dynamically determine jellyfin and dotnet versions

- .editorconfig
- .github/workflows/CI.yml
- More output for unit testing
- Trigger more errors in editorconfig
> ci: adjust errors and testing output

- Jellyfin.Plugin.Themerr.Tests/TestThemerrController.cs
- Jellyfin.Plugin.Themerr/Api/ThemerrController.cs
- Jellyfin.Plugin.Themerr/Configuration/configPage.html
- Locale/en.json
Logic needs to be modified to handle longer timeouts.
Todo:
- Fixes #332
> fix: modify updateProgress function to handle timeout issues

- .github/workflows/CI.yml
dotnet version was not updated in setup-dotnet action
> ci: fix dotnet-version in setup-dotnet action

- .github/workflows/CI.yml
- .github/workflows/ci-docker.yml
- .github/workflows/update-changelog.yml
- .github/workflows/update-jellyfin-release.yml
> ci: use prerelease logic

- .github/workflows/update-jellyfin-release.yml
Only update jellyfin repo if running in LizardByte org.
> ci: only update jellyfin repo if running in LizardByte org

- .github/workflows/update-jellyfin-release.yml
PAT is required for this workflow.
> ci: fix missing permission in update-jellyfin-release.yml

- .github/workflows/update-jellyfin-release.yml
repoLabels is not properly being initialized.
> ci: fix octokit in update-jellyfin-release.yml

- .github/workflows/update-jellyfin-release.yml
> ci: more update-jellyfin-release.yml fixes

- .github/workflows/update-jellyfin-release.yml
More fixes for release event workflow.
Test loop works:
```txt
/home/runner/work/Themerr-jellyfin/Themerr-jellyfin/release_downloads/themerr-jellyfin.zip
Archive:  /home/runner/work/Themerr-jellyfin/Themerr-jellyfin/release_downloads/themerr-jellyfin.zip
inflating: ./release_downloads/0/Jellyfin.Plugin.Themerr.dll  
inflating: ./release_downloads/0/meta.json  
inflating: ./release_downloads/0/YoutubeExplode.dll  
inflating: ./release_downloads/0/themerr-jellyfin.png  
found plugin: /home/runner/work/Themerr-jellyfin/Themerr-jellyfin/release_downloads/themerr-jellyfin.zip
```
[Allow edits from …
> ci: fix check download assets

- .github/workflows/update-jellyfin-release.yml
> build(deps): bump LizardByte/jellyfin-plugin-action from v2024.522.143446 to v2024.523.204421
